### ISSUE TITLE
这玩意不是通用的吗 怎么每年都搞个新的

### ISSUE THREAD

**Issue by EzraRT** [IllyasvielEin/RoboCup3dInstaller#1]

**Comment by IllyasvielEin** [comment]
> 

草原来是这里露出来的，我正说我一直在隔壁更新你怎么知道

**Comment by EzraRT** [comment]
我劝你谨慎 不要来 换 来 更改 我们最好的的ubuntu18

**Comment by IllyasvielEin** [comment]
> 我劝你谨慎 不要来 换 来 更改 我们最好的的ubuntu18

没想到我的第一份issue是这样的 能不能正式一点
